/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ArqueoCaja;

import OperacionesContabilidad.Operaciones;

/**
 *
 * @author luis
 */
public class InterfaceArqueoCaja extends javax.swing.JFrame {
    
    //**************************************************************************************************************
    //*************************************  ATRIBUTOS  ************************************************************
    //**************************************************************************************************************
   
    private Operaciones op;
    
    //**************************************************************************************************************
    //*************************************  CONSTRUCTORES  ********************************************************
    //**************************************************************************************************************
 
    public InterfaceArqueoCaja() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
    }
    
    public InterfaceArqueoCaja(Operaciones op) {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        this.op = op;
                
    }
    
    //**************************************************************************************************************
    //***********************************  METODOS  PUBLICOS  ******************************************************
    //**************************************************************************************************************
 
    public void obtenerTotalArqueo() {
        Double total50 = op.obtenerTotalTxT(txtTotal50);
        Double total20 = op.obtenerTotalTxT(txtTotal20);
        Double total10 = op.obtenerTotalTxT(txtTotal10);
        Double total5 = op.obtenerTotalTxT(txtTotal5);
        Double total2 = op.obtenerTotalTxT(txtTotal2);
        Double total1 = op.obtenerTotalTxT(txtTotal1);
        Double total050 = op.obtenerTotalTxT(txtTotal050);
        Double total020 = op.obtenerTotalTxT(txtTotal020);
        Double total010 = op.obtenerTotalTxT(txtTotal010);
        Double total005 = op.obtenerTotalTxT(txtTotal005);
        Double total002 = op.obtenerTotalTxT(txtTotal002);
        Double total001 = op.obtenerTotalTxT(txtTotal001);
        Double totalArqueo = total50 + total20 + total10 + total5 + total2 + total1
                + total050 + total020 + total010 + total005 + total002 + total001;
        totalArqueo = op.redondear(totalArqueo);
        txtTotalArqueo.setText(totalArqueo + "");
    }
    
    //**************************************************************************************************************
    //***********************************  METODOS PRIVADOS  *******************************************************
    //**************************************************************************************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNum50 = new javax.swing.JTextField();
        txtNum20 = new javax.swing.JTextField();
        txtNum10 = new javax.swing.JTextField();
        txtNum5 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        txtNum050 = new javax.swing.JTextField();
        txtNum020 = new javax.swing.JTextField();
        txtNum010 = new javax.swing.JTextField();
        txtNum005 = new javax.swing.JTextField();
        txtNum002 = new javax.swing.JTextField();
        txtNum001 = new javax.swing.JTextField();
        txtTotal50 = new javax.swing.JTextField();
        txtTotal20 = new javax.swing.JTextField();
        txtTotal10 = new javax.swing.JTextField();
        txtTotal5 = new javax.swing.JTextField();
        txtTotal2 = new javax.swing.JTextField();
        txtTotal1 = new javax.swing.JTextField();
        txtTotal050 = new javax.swing.JTextField();
        txtTotal020 = new javax.swing.JTextField();
        txtTotal010 = new javax.swing.JTextField();
        txtTotal005 = new javax.swing.JTextField();
        txtTotal002 = new javax.swing.JTextField();
        txtTotal001 = new javax.swing.JTextField();
        txtTotalArqueo = new javax.swing.JTextField();
        btnVolverMenu = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("20 € :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("10 € :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("5 € :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("2 € :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("1 € :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 255));
        jLabel16.setText("€");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 20, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setText("0.20 € :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setText("0.10 € :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setText("0.05 € :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 255));
        jLabel20.setText("Total : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 255));
        jLabel21.setText("50 € :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("0.02 € :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jLabel23.setText("0.01 € :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        txtNum50.setBackground(new java.awt.Color(102, 102, 255));
        txtNum50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum50.setForeground(new java.awt.Color(204, 255, 255));
        txtNum50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum50KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum50KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, 30));

        txtNum20.setBackground(new java.awt.Color(102, 102, 255));
        txtNum20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum20.setForeground(new java.awt.Color(204, 255, 255));
        txtNum20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum20KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum20KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 30));

        txtNum10.setBackground(new java.awt.Color(102, 102, 255));
        txtNum10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum10.setForeground(new java.awt.Color(204, 255, 255));
        txtNum10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum10KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum10KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 30));

        txtNum5.setBackground(new java.awt.Color(102, 102, 255));
        txtNum5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum5.setForeground(new java.awt.Color(204, 255, 255));
        txtNum5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum5KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 30));

        txtNum2.setBackground(new java.awt.Color(102, 102, 255));
        txtNum2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum2.setForeground(new java.awt.Color(204, 255, 255));
        txtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum2KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, 30));

        txtNum1.setBackground(new java.awt.Color(102, 102, 255));
        txtNum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(204, 255, 255));
        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum1KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, 30));

        txtNum050.setBackground(new java.awt.Color(102, 102, 255));
        txtNum050.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum050.setForeground(new java.awt.Color(204, 255, 255));
        txtNum050.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum050KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum050KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum050, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, 30));

        txtNum020.setBackground(new java.awt.Color(102, 102, 255));
        txtNum020.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum020.setForeground(new java.awt.Color(204, 255, 255));
        txtNum020.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum020KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum020KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum020, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 80, 30));

        txtNum010.setBackground(new java.awt.Color(102, 102, 255));
        txtNum010.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum010.setForeground(new java.awt.Color(204, 255, 255));
        txtNum010.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum010KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum010KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum010, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 80, 30));

        txtNum005.setBackground(new java.awt.Color(102, 102, 255));
        txtNum005.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum005.setForeground(new java.awt.Color(204, 255, 255));
        txtNum005.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum005KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum005KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum005, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 80, 30));

        txtNum002.setBackground(new java.awt.Color(102, 102, 255));
        txtNum002.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum002.setForeground(new java.awt.Color(204, 255, 255));
        txtNum002.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum002KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum002KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum002, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 80, 30));

        txtNum001.setBackground(new java.awt.Color(102, 102, 255));
        txtNum001.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum001.setForeground(new java.awt.Color(204, 255, 255));
        txtNum001.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNum001KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum001KeyTyped(evt);
            }
        });
        getContentPane().add(txtNum001, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 80, 30));

        txtTotal50.setEditable(false);
        txtTotal50.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal50.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 80, 30));

        txtTotal20.setEditable(false);
        txtTotal20.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal20.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 80, 30));

        txtTotal10.setEditable(false);
        txtTotal10.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal10.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 80, 30));

        txtTotal5.setEditable(false);
        txtTotal5.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal5.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, 30));

        txtTotal2.setEditable(false);
        txtTotal2.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal2.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 80, 30));

        txtTotal1.setEditable(false);
        txtTotal1.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal1.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 80, 30));

        txtTotal050.setEditable(false);
        txtTotal050.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal050.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal050.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal050, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 80, 30));

        txtTotal020.setEditable(false);
        txtTotal020.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal020.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal020.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal020, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 80, 30));

        txtTotal010.setEditable(false);
        txtTotal010.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal010.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal010.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal010, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 80, 30));

        txtTotal005.setEditable(false);
        txtTotal005.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal005.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal005.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal005, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 80, 30));

        txtTotal002.setEditable(false);
        txtTotal002.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal002.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal002.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal002, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 80, 30));

        txtTotal001.setEditable(false);
        txtTotal001.setBackground(new java.awt.Color(102, 102, 255));
        txtTotal001.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal001.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotal001, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 80, 30));

        txtTotalArqueo.setEditable(false);
        txtTotalArqueo.setBackground(new java.awt.Color(102, 102, 255));
        txtTotalArqueo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalArqueo.setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTotalArqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 80, 30));

        btnVolverMenu.setBackground(new java.awt.Color(0, 102, 153));
        btnVolverMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(204, 255, 255));
        btnVolverMenu.setText("Vovel Menu Principal");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 180, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 255));
        jLabel24.setText("0.50 € :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 255));
        jLabel25.setText("€");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 20, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 255));
        jLabel26.setText("€");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 20, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 255));
        jLabel27.setText("€");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 20, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 255));
        jLabel28.setText("€");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 20, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 255));
        jLabel29.setText("€");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 20, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 255));
        jLabel30.setText("€");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 20, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 255));
        jLabel31.setText("€");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 20, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 255));
        jLabel32.setText("€");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 20, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 255));
        jLabel33.setText("€");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 20, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 255));
        jLabel34.setText("€");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 20, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 255));
        jLabel35.setText("€");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 20, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 255));
        jLabel36.setText("€");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 272, 20, 30));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/0fb61e91-f714-41e8-9f27-1c2f77a31284image6.png"))); // NOI18N
        getContentPane().add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void txtNum50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum50KeyReleased
        // TODO add your handling code here:        
        op.llenarTotalNum(txtNum50,txtTotal50,50);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum50KeyReleased

    private void txtNum50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum50KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum50KeyTyped

    private void txtNum20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum20KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum20,txtTotal20,20);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum20KeyReleased

    private void txtNum20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum20KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum20KeyTyped

    private void txtNum10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum10KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum10,txtTotal10,10);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum10KeyReleased

    private void txtNum10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum10KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum10KeyTyped

    private void txtNum5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum5KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum5,txtTotal5,5);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum5KeyReleased

    private void txtNum5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum5KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum5KeyTyped

    private void txtNum2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum2,txtTotal2,2);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum2KeyReleased

    private void txtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum2KeyTyped

    private void txtNum1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum1,txtTotal1,1);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum1KeyReleased

    private void txtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum1KeyTyped

    private void txtNum050KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum050KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum050,txtTotal050,0.50);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum050KeyReleased

    private void txtNum050KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum050KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum050KeyTyped

    private void txtNum020KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum020KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum020,txtTotal020,0.20);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum020KeyReleased

    private void txtNum020KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum020KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum020KeyTyped

    private void txtNum010KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum010KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum010,txtTotal010,0.10);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum010KeyReleased

    private void txtNum010KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum010KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum010KeyTyped

    private void txtNum005KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum005KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum005,txtTotal005,0.05);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum005KeyReleased

    private void txtNum005KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum005KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum005KeyTyped

    private void txtNum002KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum002KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum002,txtTotal002,0.02);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum002KeyReleased

    private void txtNum002KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum002KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum002KeyTyped

    private void txtNum001KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum001KeyReleased
        // TODO add your handling code here:
        op.llenarTotalNum(txtNum001,txtTotal001,0.01);
        obtenerTotalArqueo();
    }//GEN-LAST:event_txtNum001KeyReleased

    private void txtNum001KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum001KeyTyped
        // TODO add your handling code here:
        op.onlyNum(evt);
    }//GEN-LAST:event_txtNum001KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JTextField txtNum001;
    private javax.swing.JTextField txtNum002;
    private javax.swing.JTextField txtNum005;
    private javax.swing.JTextField txtNum010;
    private javax.swing.JTextField txtNum020;
    private javax.swing.JTextField txtNum050;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum10;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum20;
    private javax.swing.JTextField txtNum5;
    private javax.swing.JTextField txtNum50;
    private javax.swing.JTextField txtTotal001;
    private javax.swing.JTextField txtTotal002;
    private javax.swing.JTextField txtTotal005;
    private javax.swing.JTextField txtTotal010;
    private javax.swing.JTextField txtTotal020;
    private javax.swing.JTextField txtTotal050;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotal10;
    private javax.swing.JTextField txtTotal2;
    private javax.swing.JTextField txtTotal20;
    private javax.swing.JTextField txtTotal5;
    private javax.swing.JTextField txtTotal50;
    private javax.swing.JTextField txtTotalArqueo;
    // End of variables declaration//GEN-END:variables
}
