/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

import OperacionesContabilidad.Operaciones;

/**
 *
 * @author luis
 */
public class InterfaceClienteMenu extends javax.swing.JFrame {
    
    //**************************************************************************************************************
    //*************************************  ATRIBUTOS  ************************************************************
    //**************************************************************************************************************
   
    private Operaciones op;
    
    //**************************************************************************************************************
    //*************************************  CONSTRUCTORES  ********************************************************
    //**************************************************************************************************************

    public InterfaceClienteMenu() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
    }
    
    public InterfaceClienteMenu(Operaciones op) {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        this.op = op;
    }
    
    //**************************************************************************************************************
    //**************************************  METODOS  PUBLICOS  ***************************************************
    //**************************************************************************************************************
 

    
    //**************************************************************************************************************
    //**************************************  METODOS PRIVADOS  ****************************************************
    //**************************************************************************************************************
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarCliente = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarCliente.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 60));

        btnConsultarCliente.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsultarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnConsultarCliente.setText("Consultar Cliente");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 200, 60));

        btnCrearCliente.setBackground(new java.awt.Color(102, 102, 255));
        btnCrearCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCrearCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnCrearCliente.setText("Crear Cliente");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 220, 60));

        btnModificarCliente.setBackground(new java.awt.Color(102, 102, 255));
        btnModificarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnModificarCliente.setText("Modificar Cliente");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 60));

        btnVolverMenuPrincipal.setBackground(new java.awt.Color(102, 102, 255));
        btnVolverMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolverMenuPrincipal.setForeground(new java.awt.Color(204, 204, 204));
        btnVolverMenuPrincipal.setText("Volver Menu Principal");
        btnVolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/índice.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, -1));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        getContentPane().add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        InterfaceCrearCliente icc = new InterfaceCrearCliente(op);
        icc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        // TODO add your handling code here:
        InterfaceModificarCliente imc = new InterfaceModificarCliente(op);
        imc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        InterfaceEliminarCliente iec = new InterfaceEliminarCliente(op);
        iec.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        // TODO add your handling code here:
        InterfaceConsultarCliente icc = new InterfaceConsultarCliente(op);
        icc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnVolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverMenuPrincipalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnVolverMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagenFondo;
    // End of variables declaration//GEN-END:variables
}
