/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Configuracion;

import OperacionesContabilidad.Operaciones;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author luis
 */
public class InterfaceConfiguracionMenu extends javax.swing.JFrame {
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 
    private Operaciones op;
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 

    /**
     * Creates new form InterfaceConfiguracionMenu
     */
    public InterfaceConfiguracionMenu() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        setTitle("Configuracion");
        cerrar();
    }
    
    public InterfaceConfiguracionMenu(Operaciones op) {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        setTitle("Configuracion");
        this.op = op;
        cerrar();
    }
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 
    
         /* Metodo para salir de una ventana */
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
              public void windowClosing(WindowEvent e){
                  //confirmarSalida();
                  dispose();
              }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnModPorcSeccion = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();
        btnConsultarUsuario = new javax.swing.JButton();
        btnCrearSuper = new javax.swing.JButton();
        btnConsultarSuper = new javax.swing.JButton();
        btnModificarSuper = new javax.swing.JButton();
        btnEliminarSuper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setText("Modificar Usuario");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        btnModPorcSeccion.setText("Modificar Porcentaje Secciones");

        btnVolverMenuPrincipal.setText("Volver Menu Principal");
        btnVolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPrincipalActionPerformed(evt);
            }
        });

        btnConsultarUsuario.setText("Consultar Usuario");
        btnConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarUsuarioActionPerformed(evt);
            }
        });

        btnCrearSuper.setText("Crear Supermercado");
        btnCrearSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSuperActionPerformed(evt);
            }
        });

        btnConsultarSuper.setText("Consultar Supermercado");
        btnConsultarSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSuperActionPerformed(evt);
            }
        });

        btnModificarSuper.setText("Modificar Supermercado");
        btnModificarSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSuperActionPerformed(evt);
            }
        });

        btnEliminarSuper.setText("Eliminar Supermercado");
        btnEliminarSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSuperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolverMenuPrincipal)
                    .addComponent(btnModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModPorcSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarSuper, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnModificarSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUsuario)
                    .addComponent(btnCrearSuper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarUsuario)
                    .addComponent(btnConsultarSuper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarUsuario)
                    .addComponent(btnModificarSuper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarUsuario)
                    .addComponent(btnEliminarSuper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModPorcSeccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnVolverMenuPrincipal)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        InterfaceCrearUsuario icc = new InterfaceCrearUsuario(op);
        icc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfaceConsultarUsuario icu = new InterfaceConsultarUsuario(op);
        icu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultarUsuarioActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfaceModificarUsuario imu = new InterfaceModificarUsuario(op);
        imu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfaceEliminarUsuario ieu = new InterfaceEliminarUsuario(op);
        ieu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnVolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverMenuPrincipalActionPerformed

    private void btnCrearSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSuperActionPerformed
        // TODO add your handling code here:
        InterfaceCrearSuper ics = new InterfaceCrearSuper(op);
        ics.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearSuperActionPerformed

    private void btnConsultarSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSuperActionPerformed
        // TODO add your handling code here:
        InterfaceConsultarSuper ics = new InterfaceConsultarSuper(op);
        ics.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultarSuperActionPerformed

    private void btnModificarSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSuperActionPerformed
        // TODO add your handling code here:
        InterfaceModificarSuper ims = new InterfaceModificarSuper(op);
        ims.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarSuperActionPerformed

    private void btnEliminarSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSuperActionPerformed
        // TODO add your handling code here:
        InterfaceEliminarSuper ies = new InterfaceEliminarSuper(op);
        ies.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarSuperActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarSuper;
    private javax.swing.JButton btnConsultarUsuario;
    private javax.swing.JButton btnCrearSuper;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEliminarSuper;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModPorcSeccion;
    private javax.swing.JButton btnModificarSuper;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnVolverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
