/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio_Menu;

import OperacionesContabilidad.Operaciones;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class InterfaceInicioPrograma extends javax.swing.JFrame {
    
    private Operaciones opmi;
    private Connection reg;
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
    
    /**
     * Creates new form InterfaceInicioPrograma
     */
    public InterfaceInicioPrograma() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        opmi.obtenerDatosUsuariosCombo(comboUsuario);
    }
    
    public InterfaceInicioPrograma(Operaciones opmi, Connection reg) {
        this.opmi = opmi;
        this.reg = reg;
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        opmi.obtenerDatosUsuariosCombo(comboUsuario);
    }
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
    
    public Operaciones getOpmi() {
        return opmi;
    }

    public void setOpmi(Operaciones opmi) {
        this.opmi = opmi;
    }

    public Connection getreg() {
        return reg;
    }

    public void setCon(Connection reg) {
        this.reg = reg;
    }

    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        lblImagenUser = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        comboUsuario = new javax.swing.JComboBox<>();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setBackground(new java.awt.Color(0, 0, 51));
        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 100, 50));

        lblImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_256.png"))); // NOI18N
        getContentPane().add(lblImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 260));

        btnSalir.setBackground(new java.awt.Color(0, 0, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 100, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txtPassword.setBackground(new java.awt.Color(0, 0, 51));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 260, -1));

        comboUsuario.setBackground(new java.awt.Color(0, 0, 51));
        comboUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(comboUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 260, -1));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo3.jpg"))); // NOI18N
        lblImagenFondo.setText("jLabel3");
        getContentPane().add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        String user = comboUsuario.getSelectedItem().toString();
        //String password = txtPassword.getText();
        String password = "ciervo9327";
        if (opmi.esCorrectoUsuario(user, password)) {
            InterfaceMenuPrograma imp = new InterfaceMenuPrograma(opmi);
            imp.setVisible(true);
            dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Incorrecto", "Gracias", JOptionPane.INFORMATION_MESSAGE);         
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> comboUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblImagenUser;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
