/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedores;

import OperacionesContabilidad.Operaciones;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author luis
 */
public class InterfaceConsultaProveedorDatos extends javax.swing.JFrame {
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
   
    private Operaciones op;
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 

    /**
     * Creates new form InterfaceConsultarUsuarioDatos
     */
    public InterfaceConsultaProveedorDatos() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        setTitle("Consultar proveedor");
        llenarDatosProveedor();
        cerrar();
    }
    
    public InterfaceConsultaProveedorDatos(Operaciones op) {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        setResizable(false); // permite que la ventana no se pueda maximizar
        setTitle("Consultar proveedor");
        this.op = op;
        llenarDatosProveedor();
        cerrar();
    }
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 
    
    public void llenarDatosProveedor (){
        ArrayList<Proveedor> prov = op.getProveedores();
        Integer indice = op.getIndiceProveedor();
        txtNombre_Proveedor.setText(prov.get(indice).getNombre_Proveedor());
        txtDomicilio_Proveedor.setText(prov.get(indice).getDomicilio_Proveedor());
        txtLocalidad_Proveedor.setText(prov.get(indice).getLocalidad_Proveedor());
        txtProvincia_Proveedor.setText(prov.get(indice).getProvincia_Proveedor());        
        txtNIF_Proveedor.setText(prov.get(indice).getNif_Proveedor());
        txtTelefono_Proveedor.setText(prov.get(indice).getTelefono_Proveedor().toString());
        txtEmail_Proveedor.setText(prov.get(indice).getEmail_Proveedor());
        txtSupermercado_Proveedor.setText(op.obtenerNombreSuper(prov.get(indice).getId_Super_Proveedor()));   
    }
    
         /* Metodo para salir de una ventana */
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
              public void windowClosing(WindowEvent e){
                  //confirmarSalida();
                  dispose();
              }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
    
    //**************************************************************************************************************
    //**************************************************************************************************************
    //**************************************************************************************************************
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNIF_Proveedor = new javax.swing.JTextField();
        txtTelefono_Proveedor = new javax.swing.JTextField();
        txtProvincia_Proveedor = new javax.swing.JTextField();
        txtLocalidad_Proveedor = new javax.swing.JTextField();
        txtDomicilio_Proveedor = new javax.swing.JTextField();
        txtNombre_Proveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail_Proveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupermercado_Proveedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre : ");

        jLabel3.setText("Domicilio : ");

        jLabel4.setText("Localidad : ");

        jLabel5.setText("Provincia : ");

        jLabel9.setText("NIF : ");

        jLabel10.setText("Telefono : ");

        txtNIF_Proveedor.setEditable(false);

        txtTelefono_Proveedor.setEditable(false);

        txtProvincia_Proveedor.setEditable(false);

        txtLocalidad_Proveedor.setEditable(false);

        txtDomicilio_Proveedor.setEditable(false);

        txtNombre_Proveedor.setEditable(false);

        jLabel2.setText("Email : ");

        txtEmail_Proveedor.setEditable(false);
        txtEmail_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_ProveedorActionPerformed(evt);
            }
        });

        jLabel6.setText("Supermercado :");

        txtSupermercado_Proveedor.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefono_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(txtNIF_Proveedor)
                    .addComponent(txtProvincia_Proveedor)
                    .addComponent(txtLocalidad_Proveedor)
                    .addComponent(txtDomicilio_Proveedor)
                    .addComponent(txtNombre_Proveedor)
                    .addComponent(txtEmail_Proveedor)
                    .addComponent(txtSupermercado_Proveedor))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilio_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocalidad_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvincia_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIF_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSupermercado_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmail_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_ProveedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDomicilio_Proveedor;
    private javax.swing.JTextField txtEmail_Proveedor;
    private javax.swing.JTextField txtLocalidad_Proveedor;
    private javax.swing.JTextField txtNIF_Proveedor;
    private javax.swing.JTextField txtNombre_Proveedor;
    private javax.swing.JTextField txtProvincia_Proveedor;
    private javax.swing.JTextField txtSupermercado_Proveedor;
    private javax.swing.JTextField txtTelefono_Proveedor;
    // End of variables declaration//GEN-END:variables
}
