/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedores;

import OperacionesContabilidad.Operaciones;

/**
 *
 * @author luis
 */
public class InterfaceProveedorMenu extends javax.swing.JFrame {
    
    //**************************************************************************************************************
    //*************************************  ATRIBUTOS  ************************************************************
    //**************************************************************************************************************
   
    private Operaciones op;
    
    //**************************************************************************************************************
    //*************************************  CONSTRUCTORES  ********************************************************
    //**************************************************************************************************************

    public InterfaceProveedorMenu() {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
    }
    
    public InterfaceProveedorMenu(Operaciones op) {
        initComponents();
        setLocationRelativeTo(null);//permite que la ventana aparezca centrada
        this.op = op;
    }
    
    //**************************************************************************************************************
    //**************************************  METODOS  PUBLICOS  ***************************************************
    //**************************************************************************************************************
 

    
    //**************************************************************************************************************
    //**************************************  METODOS PRIVADOS  ****************************************************
    //**************************************************************************************************************
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarProveedor = new javax.swing.JButton();
        lblImagenIcono = new javax.swing.JLabel();
        btnConsultarProveedor = new javax.swing.JButton();
        btnCrearProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarProveedor.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminarProveedor.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarProveedor.setText("Eliminar Proveedor");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 60));

        lblImagenIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/slideshow3.png"))); // NOI18N
        getContentPane().add(lblImagenIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 290));

        btnConsultarProveedor.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsultarProveedor.setForeground(new java.awt.Color(204, 204, 204));
        btnConsultarProveedor.setText("Consultar Proveedor");
        btnConsultarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, 60));

        btnCrearProveedor.setBackground(new java.awt.Color(102, 102, 255));
        btnCrearProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCrearProveedor.setForeground(new java.awt.Color(204, 204, 204));
        btnCrearProveedor.setText("Crear Proveedor");
        btnCrearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 220, 60));

        btnModificarProveedor.setBackground(new java.awt.Color(102, 102, 255));
        btnModificarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificarProveedor.setForeground(new java.awt.Color(204, 204, 204));
        btnModificarProveedor.setText("Modificar Proveedor");
        btnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 60));

        btnVolverMenuPrincipal.setBackground(new java.awt.Color(102, 102, 255));
        btnVolverMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolverMenuPrincipal.setForeground(new java.awt.Color(204, 204, 204));
        btnVolverMenuPrincipal.setText("Volver Menu Principal");
        btnVolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, 60));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        getContentPane().add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProveedorActionPerformed
        // TODO add your handling code here:
        InterfaceCrearProveedor icp = new InterfaceCrearProveedor(op);
        icp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearProveedorActionPerformed

    private void btnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProveedorActionPerformed
        // TODO add your handling code here:
        InterfaceModificarProveedor imp = new InterfaceModificarProveedor(op);
        imp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        InterfaceEliminarProveedor iep = new InterfaceEliminarProveedor(op);
        iep.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnConsultarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProveedorActionPerformed
        // TODO add your handling code here:
        InterfaceConsultarProveedor icp = new InterfaceConsultarProveedor(op);
        icp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultarProveedorActionPerformed

    private void btnVolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverMenuPrincipalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarProveedor;
    private javax.swing.JButton btnCrearProveedor;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnModificarProveedor;
    private javax.swing.JButton btnVolverMenuPrincipal;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblImagenIcono;
    // End of variables declaration//GEN-END:variables
}
